services:
  - type: web
    name: ai-attendance-server
    env: java
    rootDirectory: server
    buildCommand: chmod +x mvnw && ./mvnw clean install -DskipTests
    startCommand: java -jar target/ai-attendance-system-0.0.1-SNAPSHOT.jar
    envVars:
      - key: PORT
        value: 8085
      - key: OPENCV_RESOURCE_PATH
        value: src/main/resources/opencv/haarcascade_frontalface.xml

  - type: web
    name: ai-attendance-client
    env: static
    rootDirectory: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://ai-attendance-server.onrender.com/api
